#!/bin/bash

# create a file at a given time offset with 1 minute resolution

export PATH=$PATH:.

rm file_column.ngr
ngr create -f file_column.ngr -b 1258091219 -r 60 -c 2

# insert multiple values
ngr insert -f file_column.ngr -t 1258091219 -c 0 -v 1
ngr insert -f file_column.ngr -t 1258091279 -c 0 -v 2
ngr insert -f file_column.ngr -t 1258091339 -c 0 -v 3
ngr insert -f file_column.ngr -t 1258091399 -c 0 -v 4
ngr insert -f file_column.ngr -t 1258091459 -c 0 -v 5
ngr insert -f file_column.ngr -t 1258091519 -c 0 -v 6
ngr insert -f file_column.ngr -t 1258091579 -c 0 -v 7
ngr insert -f file_column.ngr -t 1258091639 -c 0 -v 8
ngr insert -f file_column.ngr -t 1258091699 -c 0 -v 9
ngr insert -f file_column.ngr -t 1258091219 -c 1 -v 9
ngr insert -f file_column.ngr -t 1258091279 -c 1 -v 8
ngr insert -f file_column.ngr -t 1258091339 -c 1 -v 7
ngr insert -f file_column.ngr -t 1258091399 -c 1 -v 6
ngr insert -f file_column.ngr -t 1258091459 -c 1 -v 5
ngr insert -f file_column.ngr -t 1258091519 -c 1 -v 4
ngr insert -f file_column.ngr -t 1258091579 -c 1 -v 3
ngr insert -f file_column.ngr -t 1258091639 -c 1 -v 2
ngr insert -f file_column.ngr -t 1258091699 -c 1 -v 1

# see raw content
ngr dump -f file_column.ngr

#see info 
ngr info -f file_column.ngr

ngr agg -f file_column.ngr -s 1258091219 -e 1258091699 -i 120


