#!/bin/bash

# create a file at a given time offset with 1 minute resolution

export PATH=$PATH:.

rm file.tsdb
tsdb create -f file.tsdb -b 1258091219 -r 60 -c 1

# insert multiple values
tsdb insert -f file.tsdb -t 1258091219 -v 1
tsdb insert -f file.tsdb -t 1258091279 -v 2
tsdb insert -f file.tsdb -t 1258091339 -v 3
tsdb insert -f file.tsdb -t 1258091399 -v 4
tsdb insert -f file.tsdb -t 1258091459 -v 5
tsdb insert -f file.tsdb -t 1258091519 -v 6
tsdb insert -f file.tsdb -t 1258091579 -v 7
tsdb insert -f file.tsdb -t 1258091639 -v 8
tsdb insert -f file.tsdb -t 1258091699 -v 9

# see raw content
tsdb dump -f file.tsdb

#see info 
tsdb info -f file.tsdb

tsdb agg -f file.tsdb -s 1258091219 -e 1258091699 -i 120


